services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./prisma:/app/prisma
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/dev.db
    restart: always
